apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: jenkins
data:
  config.json: |
    {
      "credHelpers": {
        "381492144666.dkr.ecr.eu-west-1.amazonaws.com": "ecr-login"
      }
    }