image:
  repository: 381492144666.dkr.ecr.eu-west-1.amazonaws.com/lesson-8-9-ecr
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi